# Default configuration for Theo

# Application directories
log_dir: "./log/"
var_dir: "./var/"

# Assistant settings
assistant_name: "Theo"
startup_prompts:
  - "Say Hello World! or whatever fun salutation you prefer"

# Logging settings
logging_level: "INFO"
file_logging_enabled: true
save_camera_images: false

# Realtime audio detection
prefix_padding_ms: 500
silence_threshold: 0.2
silence_duration_ms: 900
